### PR TITLE
Translate guidance-naming-conventions.md

### PR DESCRIPTION
**Pull request by yfakariya**
I translated guidance-naming-conventions.md because I think this article is important for many Japaense people including non-experts.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yfakariya__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by yfakariya** [comment]
Sorry, I found a few typos and fixed them

**Comment by v-malemo** [comment]
@yfakariya. Thank you for your feedback and suggestion! 
		
This file has not been localized in the past because it is currently out of the localization scope. As a result we need to reject your contribution, which is not fully aligned to our acceptance criterial. I am closing this PR. 

Microsoft C&E Localization Team

**Comment by yfakariya** [comment]
Okey, I understood why this pr was closed. But I think this article is very important for Japanese people who don't try to read English. So, can we(community members) request localization or can we know the your plan?

**Comment by SunnyDeng** [comment]
@yfakariya, to follow up with this request, your contribution was tweeted to https://twitter.com/satonaoki/status/779130342917545984, and retweeted many times already(!).
Thank you very much for the contribution!

**Pull request closed without merging**
