### PR TITLE
Improve translation

### PR DESCRIPTION
**Pull request by nnasaki**
`SSL 終了` is means like SSL is finished. I'd like to propose a more better translation.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nnasaki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by nnasaki** [comment]
@v-malemo Could you wait for merge this PR. I have got similar points in other documents now. I will fix it now.

**Comment by v-malemo** [comment]
@nnasaki Sure, absolutely. Thank you again for your contribution.

**Comment by nnasaki** [comment]
@v-malemo Thank you. I'm doing now while watching dotnetConf :)

**Comment by buchizo** [comment]
LGTM

**Comment by nnasaki** [comment]
@v-malemo The translations done. Could you review it?

**Comment by v-malemo** [comment]
@nnasaki The language expert is reviewing the suggested corrections. We will keep you informed on this PR resolution. Thank you in advance.

**Comment by v-malemo** [comment]
@nnasaki , Thank you for your feedback and suggestion! 
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
Microsoft C&E Localization Team

**Comment by nnasaki** [comment]
@v-malemo Thank you!

**Pull request merged**
