### PR TITLE
Fixing Mistranslation

### PR DESCRIPTION
**Pull request by kiyokura**
`Azure subscription` is `Azure サブスクリプション` in Japanese.
(`として機能します` means like `It will function as ...`.)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kiyokura__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@kiyokura__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by v-malemo** [comment]
@kiyokura, Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 

Microsoft C&E Localization Team

**Comment by azurecla** [comment]
Hi __@kiyokura__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Pull request merged**
