### PR TITLE
Update virtual-machines-linux-vm-monitoring.md

### PR DESCRIPTION
**Pull request by yuyalush**
fix linked document.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yuyalush__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by v-malemo** [comment]
Hi @yuyalush, we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-malemo** [comment]
Hi @yuyalush, we are still in discussing, will update the decision later soon.

Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-malemo** [comment]
Hi @yuyalush, we are still in discussing, will update the decision later soon.

Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-malemo** [comment]
Hi @yuyalush, we are still in discussing, will update the decision later soon.

Thanks for your support,

Microsoft C&E Localization Team

**Pull request closed without merging**
